name: Terraform Triage Apply

on:
  workflow_dispatch:

env:
  # Azure Credentials
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  apply:
    runs-on: ubuntu-latest
    environment:
      name: triage-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-triage
          path: triage

      - name: Terraform Init
        run: terraform init
        working-directory: triage

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: triage
